name: Modify Manifest

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: 'false'
        default: 'No source specified'

jobs:
  modify_manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: modify manifest
        run: bash modify_manifest.sh
      - name: setup git config
        run: |
          git config user.name "Github manifest modifier ci"
          git config user.email <>

      - name: commit
        run: |
          git add io.github.spacingbat3.webcord.yml
          git commit -m "modify manifest with new release and sha256sum"
          git push orgin master
