name: Modify Manifest

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: 'No source specified'

jobs:
  modify_manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: modify manifest
        run: bash modify_manifest.sh
